name: ShEC_CSE
description: "A new Flutter project."

version: 1.0.0+1

environment:
  sdk: '>=3.11.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  url_launcher: ^6.3.2
  image_picker: ^1.2.1
  image_cropper: ^12.2.1
  http: ^1.6.0
  html: ^0.15.6
  supabase_flutter: ^2.12.4
  flutter_dotenv: ^6.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0
  flutter_launcher_icons: ^0.14.4

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/branding/
    - assets/committee_members/
    - assets/gallery/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/branding/logo.png"

  # Optional but recommended for Android 8.0+ (Adaptive Icons)
  adaptive_icon_background: "#FFFFFF"
  adaptive_icon_foreground: "assets/branding/logo.png"